#!/usr/bin/env node
import { lstat, mkdir, readFile, readlink, rename, stat, symlink, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const rolesPath = join(repoRoot, "workflow", "roles.json");
const rolesConfig = JSON.parse(await readFile(rolesPath, "utf8"));
const roles = rolesConfig.roles;
const codexHome = resolve(process.env.CODEX_HOME?.trim() || join(homedir(), ".codex"));
const skillsDir = join(codexHome, "skills");
const agentsDir = join(codexHome, "agents");
const skillSource = join(repoRoot, "skills", "luna-workflow");
const skillTarget = join(skillsDir, "luna-workflow");

function assertRole(name) {
  const role = roles?.[name];
  if (!role || typeof role.model !== "string" || !role.model.trim()) {
    throw new Error(`workflow/roles.json is missing a model for ${name}`);
  }
  if (typeof role.reasoning !== "string" || !role.reasoning.trim()) {
    throw new Error(`workflow/roles.json is missing a reasoning level for ${name}`);
  }
  return role;
}

function tomlString(value) {
  return JSON.stringify(value);
}

function reviewerToml(role) {
  return [
    "# Generated by scripts/sync-codex.mjs; edit workflow/roles.json for model updates.",
    'name = "luna_reviewer"',
    'description = "Independent read-only Luna reviewer for a completed non-trivial change."',
    `model = ${tomlString(role.model)}`,
    `model_reasoning_effort = ${tomlString(role.reasoning)}`,
    'sandbox_mode = "read-only"',
    `developer_instructions = """\
Act as an independent, defect-first reviewer after the primary agent's direct checks.
Assess the requirements, actual bounded diff, relevant source context, acceptance criteria, and exact check results.
Use targeted read-only inspection only when necessary. Never edit, run tests or other commands, deploy, send external messages, commit, or delegate.
Report concrete, actionable defects introduced by the change, ordered by severity, with file references and observable failure conditions.
Start with 'No findings.' when there are none, then identify material evidence gaps without claiming unverified behavior passed.
"""`,
    "",
  ].join("\n");
}

function advisorToml(role) {
  return [
    "# Generated by scripts/sync-codex.mjs; edit workflow/roles.json for model updates.",
    'name = "astra_consult"',
    'description = "Astra advisor for one bounded material uncertainty; read-only and advisory."',
    `model = ${tomlString(role.model)}`,
    `model_reasoning_effort = ${tomlString(role.reasoning)}`,
    'sandbox_mode = "read-only"',
    `developer_instructions = """\
Advise the Luna primary agent on the single question in the supplied packet.
Use only the supplied facts and evidence. Focus on material uncertainty that could change design, scope, safety, or correctness.
Do not edit, run commands, deploy, send external messages, commit, or delegate.
State assumptions and the smallest defensible recommendation. If the packet lacks a fact needed to decide, name that exact fact.
The primary agent owns implementation, verification, and final judgment.
"""`,
    "",
  ].join("\n");
}

async function ensureSkillLink() {
  await mkdir(skillsDir, { recursive: true });
  try {
    const info = await lstat(skillTarget);
    if (!info.isSymbolicLink()) {
      throw new Error(`${skillTarget} already exists and is not a managed symlink; leaving it untouched`);
    }
    const existingTarget = await readlink(skillTarget);
    if (resolve(dirname(skillTarget), existingTarget) !== skillSource) {
      throw new Error(`${skillTarget} points elsewhere; leaving it untouched`);
    }
    return "already linked";
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  await symlink(skillSource, skillTarget, "dir");
  return "linked";
}

async function prepareAgent(fileName, expectedName, role, generatedContent) {
  const destination = join(agentsDir, fileName);
  try {
    const current = await readFile(destination, "utf8");
    if (current.startsWith("# Generated by scripts/sync-codex.mjs;")) {
      return { destination, content: generatedContent, mode: (await stat(destination)).mode & 0o777 };
    }

    const names = [...current.matchAll(/^\s*name\s*=\s*"([^"]+)"\s*$/gmu)];
    const models = current.match(/^\s*model\s*=.*$/gmu) ?? [];
    const efforts = current.match(/^\s*model_reasoning_effort\s*=.*$/gmu) ?? [];
    if (
      names.length !== 1 || names[0][1] !== expectedName ||
      models.length !== 1 || efforts.length !== 1 ||
      !/^\s*sandbox_mode\s*=\s*"read-only"\s*$/mu.test(current)
    ) {
      throw new Error(`${destination} is not a compatible read-only ${expectedName} profile; leaving it untouched`);
    }

    const updated = current
      .replace(/^\s*model\s*=.*$/mu, `model = ${tomlString(role.model)}`)
      .replace(/^\s*model_reasoning_effort\s*=.*$/mu, `model_reasoning_effort = ${tomlString(role.reasoning)}`);
    return { destination, content: updated, mode: (await stat(destination)).mode & 0o777 };
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  return { destination, content: generatedContent, mode: 0o600 };
}

async function writePreparedAgent(prepared) {
  await mkdir(agentsDir, { recursive: true });
  const { destination, content, mode } = prepared;
  const temporary = `${destination}.tmp-${process.pid}`;
  await writeFile(temporary, content, { encoding: "utf8", mode });
  await rename(temporary, destination);
  return destination;
}

const primary = assertRole("primary");
const advisor = assertRole("advisor");
const reviewer = assertRole("reviewer");
if (primary.reasoning !== "max") {
  throw new Error("The shared workflow requires the primary role to use max reasoning");
}
if (reviewer.reasoning !== "max" || reviewer.model !== primary.model) {
  throw new Error("The reviewer must use the primary model at max reasoning");
}
if (advisor.reasoning !== "low") {
  throw new Error("The shared workflow requires the advisor role to use low reasoning");
}

const reviewerAgent = await prepareAgent("luna_reviewer.toml", "luna_reviewer", reviewer, reviewerToml(reviewer));
const advisorAgent = await prepareAgent("astra_consult.toml", "astra_consult", advisor, advisorToml(advisor));
const linkState = await ensureSkillLink();
const reviewerPath = await writePreparedAgent(reviewerAgent);
const advisorPath = await writePreparedAgent(advisorAgent);
console.log(`Codex skill ${linkState}: ${skillTarget}`);
console.log(`Synced reviewer: ${reviewerPath}`);
console.log(`Synced advisor: ${advisorPath}`);
console.log(`Primary default: ${primary.model}:${primary.reasoning} (select through the Codex client)`);
